spring:
  config:
    name: JudgeCore-app
  main:
    web-application-type: servlet

sandbox:
  enabled: true
  command: firejail
  common-options:
    quiet: true
    seccomp: true
    net-none: true
    no-groups: true
    no-new-privs: true
    caps-drop: all

thread:
  pool:
    executor:
      config:
        core-pool-size: 30
        max-pool-size: 80
        keep-alive-time: 5000
        block-queue-size: 8000
        policy: CallerRunsPolicy

grpc:
  server:
    port: 9000

server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 20
    accept-count: 100
    max-connections: 10000

logging:
  level:
    root: warn
    org.laoli.judge: info
  file:
    name: /app/logs/judgecore.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
