
# 沙箱配置
sandbox:
  enabled: false
  command: firejail
  common-options:
    quiet: true
    seccomp: true
    net-none: true
    no-groups: true
    no-new-privs: true
    caps-drop: all

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

grpc:
  server:
    port: 9000

# HTTP服务器配置
server:
  port: 8080

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
spring:
  main:
    web-application-type: servlet